export default function HomePage() {
  return (
    <div className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
      <header className="text-center">
        <h1 className="text-5xl font-bold text-primary">
          UX Software Marketplace
        </h1>
        <p className="mt-4 text-lg text-gray-700">
          Your new e-commerce journey starts here.
        </p>
      </header>
      <div className="mt-12">
        <p className="text-gray-400">
          Scaffold generated by Jules. Ready to build!
        </p>
      </div>
    </div>
  );
}
